language: ruby
cache: bundler
rvm:
  - 2.1
branches:
  only:
    - /.*/
    - gh-pages
before_install:
  - openssl aes-256-cbc -K $encrypted_80fa42e3877e_key -iv $encrypted_80fa42e3877e_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - echo -e "Host ci-docs.opengamma.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_script:
  - "sed -i -e 's!baseurl: \"\"!baseurl: \"/strata/'\"$TRAVIS_BRANCH\"'\"!' _config.yml"
script:
  - bundle exec jekyll build
#  - bundle exec htmlproof ./_site --check-html
after_success:
  - ssh -p 2222 -i id_rsa opengamma@ci-docs.opengamma.com mkdir -p public_html/ci-docs/strata/$TRAVIS_BRANCH
  - rsync -rve 'ssh -v -p 2222 -i id_rsa' _site/ opengamma@ci-docs.opengamma.com:public_html/ci-docs/strata/$TRAVIS_BRANCH
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

