language: ruby
cache: bundler
rvm:
  - 2.1
branches:
  only:
    - /.*/
    - gh-pages
before_install:
  - openssl aes-256-cbc -K $encrypted_80fa42e3877e_key -iv $encrypted_80fa42e3877e_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - echo -e "Host ci-docs.opengamma.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - gem update bundler
before_script:
  - "sed -i -e 's!baseurl: \".*\"!baseurl: \"/strata/'\"$TRAVIS_BRANCH\"'\"!' _config.yml"
script:
  - bundle exec jekyll build -d ./_site/strata/$TRAVIS_BRANCH
  - bundle exec htmlproofer _site --url-ignore /github.com/ --file-ignore /strata/$TRAVIS_BRANCH/apidocs/
after_success:
  - rsync -rve 'ssh -v -p 2222 -i id_rsa' _site/ opengamma@ci-docs.opengamma.com:public_html/ci-docs/
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

