baseurl: ""

exclude: [Gemfile, LICENSE.txt, README.md, vendor]

gems:
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

permalink: :title

sass:
  sass_dir: assets/stylesheets

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: "pages/intro"
    values:
      tab: "intro"

  - scope:
      path: "pages/docs"
    values:
      tab: "docs"

  - scope:
      path: "pages/community"
    values:
      tab: "community"
